### ISSUE TITLE
Add `id` to RPC request body

### ISSUE THREAD

**Issue by anudit** [0xOlias/ponder#161]
This might be a Viem thing so let me know if I should file this there.
Request to Ankr's RPC ( https://rpc.ankr.com/filecoin_testnet ) while backfilling errors out as it needs the `id` param.

Example,
Request:
```json
{
    
    "method": "eth_getLogs",
    "params": [
        {
            "address": [
                "0x0b9737ab4b3e5303cb67db031b509697e31c02d3"
            ],
            "topics": [],
            "fromBlock": "0x30f53",
            "toBlock": "0x3133B"
        }
    ]
}
```
Response:
```json
{
    "jsonrpc": "2.0",
    "error": {
        "code": -32600,
        "message": "invalid request"
    },
    "id": null
}
```

Corrected Request:
```json
{
    "id": "42",
    "method": "eth_getLogs",
    "params": [
        {
            "address": [
                "0x0b9737ab4b3e5303cb67db031b509697e31c02d3"
            ],
            "topics": [],
            "fromBlock": "0x30f53",
            "toBlock": "0x3133B"
        }
    ]
}
```
Response:
```json
{
    "jsonrpc": "2.0",
    "result": [
        {
            "address": "0x0b9737ab4b3e5303cb67db031b509697e31c02d3",
            "data": "0x",
            "topics": [
                "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",
                "0x0000000000000000000000000000000000000000000000000000000000000000",
                "0x000000000000000000000000661c77a0598d0d61f01cb6575423fad50881241b",
                "0x0000000000000000000000000000000000000000000000000000000000000001"
            ],
            "removed": false,
            "logIndex": "0x0",
            "transactionIndex": "0x0",
            "transactionHash": "0xbd5656cd2e7a675a33981818d5d86f06995916b3304efd6a6da6433f294cff70",
            "blockHash": "0xa3ec2bb6ccdcf673bdb6339f2ec2f35e8ae05f1ac23710c9df6b0cb5d5c0b78c",
            "blockNumber": "0x30f53"
        },
        {
            "address": "0x0b9737ab4b3e5303cb67db031b509697e31c02d3",
            "data": "0x000000000000000000000000661c77a0598d0d61f01cb6575423fad50881241b00000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000002e637265617465207461626c65206865616c7468626f745f333134312028636f756e74657220696e7465676572293b000000000000000000000000000000000000",
            "topics": [
                "0xfe0c067afc4fe17adcf4cfa139aabad6dc30dd86dfe39fb2b858961637156cdd"
            ],
            "removed": false,
            "logIndex": "0x1",
            "transactionIndex": "0x0",
            "transactionHash": "0xbd5656cd2e7a675a33981818d5d86f06995916b3304efd6a6da6433f294cff70",
            "blockHash": "0xa3ec2bb6ccdcf673bdb6339f2ec2f35e8ae05f1ac23710c9df6b0cb5d5c0b78c",
            "blockNumber": "0x30f53"
        },
        {
            "address": "0x0b9737ab4b3e5303cb67db031b509697e31c02d3",
            "data": "0x000000000000000000000000661c77a0598d0d61f01cb6575423fad50881241b0000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000028696e7365727420696e746f206865616c7468626f745f333134315f312076616c756573202831293b00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
            "topics": [
                "0x6de956d2cb2e161f8c91c6ae7b286358c7458d5ad5e26ea2d55330fbe282839c"
            ],
            "removed": false,
            "logIndex": "0x0",
            "transactionIndex": "0x1",
            "transactionHash": "0x797681c20f498a6c8648154461d9eaf9ea3fb06621fd3ae2dbc64e1942c77dbc",
            "blockHash": "0xb8f4c2dd84a15830774bc88ae25f5ba604044f04f74570bff819f28b745da770",
            "blockNumber": "0x30f55"
        }
    ],
    "id": "42"
}
```

**Comment by jxom** [comment]
Weird. viem definitely appends an `id` to every RPC request.

**Comment by anudit** [comment]
@jxom the error that gets logged containing the request while backfilling doesn't have the Id.

**Comment by 0xOlias** [comment]
@anudit Could you share a screenshot of the logged error?

**Comment by anudit** [comment]
@0xOlias @jxom
![image](https://user-images.githubusercontent.com/12015553/232864360-266bf929-d119-4887-8858-ff56a280829e.png)
Source Code: https://github.com/anudit/tableland-subgraph/tree/main/ponder

**Comment by 0xOlias** [comment]
Hey @anudit - were you able to get to the bottom of this?

**Comment by anudit** [comment]
@0xOlias Dug a bit deeper into this, the `id` param requirement comes from the louts node of Filecoin EVM.  

Running into the following error currently, As you can see the logged request body in the error does not have the `id` param.
```
error    - Block backfill queue error
Task:
  blockNumberToCacheFrom:  2728630
  blockNumber:             2729629
  requiredTxHashes:        [object Set]
Stack: RpcError: RPC Request failed.

URL: http://127.0.0.1:8545/api/fvm-rpc
Request body: {"method":"eth_getBlockByNumber","params":["0x29a69d",true]}

Details: failed to retrieve messages and receipts: error loading messages for tipset: [bafy2bzaceavk5owagavmx4sjpnwowwxjgede3ax6e6xmvzbqasqrwmcvnb4qi]: failed to load state tree at tipset [bafy2bzaceavk5owagavmx4sjpnwowwxjgede3ax6e6xmvzbqasqrwmcvnb4qi]: failed to load state tree bafy2bzacedrufu6ega5dk23mfeqcgvkdcv3xs4cjnut2q6tfbyp74evo4fnqi: failed to load hamt node: ipld: could not find bafy2bzacedrufu6ega5dk23mfeqcgvkdcv3xs4cjnut2q6tfbyp74evo4fnqi
Version: viem@0.1.8
    at Object.http (/Users/anudit/Documents/GitHub/tableland-subgraph/ponder/node_modules/.pnpm/viem@0.1.8_typescript@5.0.4/node_modules/viem/dist/chunk-SWM5USHJ.js:3306:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async request (/Users/anudit/Documents/GitHub/tableland-subgraph/ponder/node_modules/.pnpm/viem@0.1.8_typescript@5.0.4/node_modules/viem/dist/index.js:326:30)
    at async withRetry.delay.count.count (/Users/anudit/Documents/GitHub/tableland-subgraph/ponder/node_modules/.pnpm/viem@0.1.8_typescript@5.0.4/node_modules/viem/dist/chunk-SWM5USHJ.js:2912:16)
    at async attemptRetry (/Users/anudit/Documents/GitHub/tableland-subgraph/ponder/node_modules/.pnpm/viem@0.1.8_typescript@5.0.4/node_modules/viem/dist/chunk-SWM5USHJ.js:2852:22)
```

**Comment by anudit** [comment]
@0xOlias Debugging this more with the FEVM team, Looks like a node issue. Will update as I get more information, feel free to close this in the meanwhile.
