### ISSUE TITLE
`ponder dev`: InvalidParamsRpcError: Invalid parameters were provided to the RPC method.

### ISSUE THREAD

**Issue by pyk** [0xOlias/ponder#177]
Step by step to reproduce the issue:

```sh
pnpm create ponder
# Select None
cd my-app/
ponder dev
```

it will raise the following error:

```sh
error    - Log backfill queue error
Task:
  fromBlock:  2200567
  toBlock:    2202566
Stack: InvalidParamsRpcError: Invalid parameters were provided to the RPC method.
Double check you have provided the correct parameters.

URL: https://mainnet.chainnodes.org/29ccfee7-8d2a-450d-a94f-0322894207c0
Request body: {"method":"eth_getLogs","params":[{"address":"0x0","topics":[],"fromBlock":"0x2193f7","toBlock":"0x219bc6"}]}

Details: invalid argument 0: invalid address: hex string of odd length
Version: viem@0.3.17
    at delay.count.count (/Users/pyk/github/pyk/sushiv2-ponder/sushiv2-ponder/node_modules/.pnpm/viem@0.3.17_typescript@4.9.5/node_modules/viem/dist/cjs/utils/buildRequest.js:40:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async attemptRetry (/Users/pyk/github/pyk/sushiv2-ponder/sushiv2-ponder/node_modules/.pnpm/viem@0.3.17_typescript@4.9.5/node_modules/viem/dist/cjs/utils/promise/withRetry.js:15:30)
```

the process also cannot be killed by `CTRL+C`, need to force kill the process.

**Comment by 0xOlias** [comment]
The source of this error is the `"address":"0x0"` field. I'm not sure how/why ponder would be passing `0x0` as the address - what does your `ponder.config.ts` look like?

**Comment by pyk** [comment]
@0xOlias Ah yes, thankyou! Removing the contract object with address `0x0` in newly created ponder project fix the issue.
