### ISSUE TITLE
`ponder codegen` handle anonymous event params

### ISSUE THREAD

**Issue by pyk** [0xOlias/ponder#178]
Currently, `create-ponder` will raise an error if you use SushiV2Factory contract:

```sh
pnpm create ponder@latest --from-etherscan https://etherscan.io/address/0xc0aee478e3658e2610c5f7a4a2e1777ce9e4f2ac
```

logs:

```
✦ pnpm create ponder@latest --from-etherscan https://etherscan.io/address/0xc0aee478e3658e2610c5f7a4a2e1777ce9e4f2ac
../../Library/pnpm/store/v3/tmp/dlx-4539 |  +39 ++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /Users/pyk/Library/pnpm/store/v3
  Virtual store is at:             ../../Library/pnpm/store/v3/tmp/dlx-4539/node_modules/.pnpm
../../Library/pnpm/store/v3/tmp/dlx-4539 | Progress: resolved 39, reused 39, downloaded 0, added 39, done
✔ What is your project named? … sushiv2-ponder

Creating a new Ponder app in /Users/pyk/github/pyk/sushiv2-ponder.

Using Etherscan contract link template.

(1/2) Waiting 5 seconds for Etherscan API rate limit
(2/2) Waiting 5 seconds for Etherscan API rate limit

Installing with pnpm.

Initialized a git repository.
/Users/pyk/github/pyk/sushiv2-ponder/node_modules/.pnpm/yoga-layout-prebuilt@1.10.0/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

SyntaxError: Property or signature expected. (53:120)
  51 |                 AbiParameterToPrimitiveType<{"indexed":true,"internalType":"address","name":"token0","type":"address"}>;token1:
  52 |                 AbiParameterToPrimitiveType<{"indexed":true,"internalType":"address","name":"token1","type":"address"}>;pair:
> 53 |                 AbiParameterToPrimitiveType<{"indexed":false,"internalType":"address","name":"pair","type":"address"}>;:
     |                                                                                                                        ^
  54 |                 AbiParameterToPrimitiveType<{"indexed":false,"internalType":"uint256","name":"","type":"uint256"}>};
  55 |                 log: Log;
  56 |                 block: Block;
    at v (/Users/pyk/github/pyk/sushiv2-ponder/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/parser-typescript.js:1:14679)
    at _H (/Users/pyk/github/pyk/sushiv2-ponder/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/parser-typescript.js:49:10722)
    at Object.cH [as parse] (/Users/pyk/github/pyk/sushiv2-ponder/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/parser-typescript.js:49:11028)
    at Object.parse (/Users/pyk/github/pyk/sushiv2-ponder/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:7515:23)
    at coreFormat (/Users/pyk/github/pyk/sushiv2-ponder/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8829:18)
    at formatWithCursor2 (/Users/pyk/github/pyk/sushiv2-ponder/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:9021:18)
    at /Users/pyk/github/pyk/sushiv2-ponder/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:38183:12
    at Object.format (/Users/pyk/github/pyk/sushiv2-ponder/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:38197:12)
    at formatPrettier (/Users/pyk/github/pyk/sushiv2-ponder/node_modules/.pnpm/@ponder+core@0.0.56_typescript@4.9.5/node_modules/@ponder/core/dist/bin/ponder.js:891:34)
    at CodegenService.generateAppFile (/Users/pyk/github/pyk/sushiv2-ponder/node_modules/.pnpm/@ponder+core@0.0.56_typescript@4.9.5/node_modules/@ponder/core/dist/bin/ponder.js:949:19) {
  loc: { start: { line: 53, column: 120 } },
  codeFrame: '\x1B[0m \x1B[90m 51 |\x1B[39m                 \x1B[33mAbiParameterToPrimitiveType\x1B[39m\x1B[33m<\x1B[39m{\x1B[32m"indexed"\x1B[39m\x1B[33m:\x1B[39m\x1B[36mtrue\x1B[39m\x1B[33m,\x1B[39m\x1B[32m"internalType"\x1B[39m\x1B[33m:\x1B[39m\x1B[32m"address"\x1B[39m\x1B[33m,\x1B[39m\x1B[32m"name"\x1B[39m\x1B[33m:\x1B[39m\x1B[32m"token0"\x1B[39m\x1B[33m,\x1B[39m\x1B[32m"type"\x1B[39m\x1B[33m:\x1B[39m\x1B[32m"address"\x1B[39m}\x1B[33m>\x1B[39m\x1B[33m;\x1B[39mtoken1\x1B[33m:\x1B[39m\x1B[0m\n' +
    '\x1B[0m \x1B[90m 52 |\x1B[39m                 \x1B[33mAbiParameterToPrimitiveType\x1B[39m\x1B[33m<\x1B[39m{\x1B[32m"indexed"\x1B[39m\x1B[33m:\x1B[39m\x1B[36mtrue\x1B[39m\x1B[33m,\x1B[39m\x1B[32m"internalType"\x1B[39m\x1B[33m:\x1B[39m\x1B[32m"address"\x1B[39m\x1B[33m,\x1B[39m\x1B[32m"name"\x1B[39m\x1B[33m:\x1B[39m\x1B[32m"token1"\x1B[39m\x1B[33m,\x1B[39m\x1B[32m"type"\x1B[39m\x1B[33m:\x1B[39m\x1B[32m"address"\x1B[39m}\x1B[33m>\x1B[39m\x1B[33m;\x1B[39mpair\x1B[33m:\x1B[39m\x1B[0m\n' +
    '\x1B[0m\x1B[31m\x1B[1m>\x1B[22m\x1B[39m\x1B[90m 53 |\x1B[39m                 \x1B[33mAbiParameterToPrimitiveType\x1B[39m\x1B[33m<\x1B[39m{\x1B[32m"indexed"\x1B[39m\x1B[33m:\x1B[39m\x1B[36mfalse\x1B[39m\x1B[33m,\x1B[39m\x1B[32m"internalType"\x1B[39m\x1B[33m:\x1B[39m\x1B[32m"address"\x1B[39m\x1B[33m,\x1B[39m\x1B[32m"name"\x1B[39m\x1B[33m:\x1B[39m\x1B[32m"pair"\x1B[39m\x1B[33m,\x1B[39m\x1B[32m"type"\x1B[39m\x1B[33m:\x1B[39m\x1B[32m"address"\x1B[39m}\x1B[33m>\x1B[39m\x1B[33m;\x1B[39m\x1B[33m:\x1B[39m\x1B[0m\n' +
    '\x1B[0m \x1B[90m    |\x1B[39m                                                                                                                        \x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[0m\n' +
    '\x1B[0m \x1B[90m 54 |\x1B[39m                 \x1B[33mAbiParameterToPrimitiveType\x1B[39m\x1B[33m<\x1B[39m{\x1B[32m"indexed"\x1B[39m\x1B[33m:\x1B[39m\x1B[36mfalse\x1B[39m\x1B[33m,\x1B[39m\x1B[32m"internalType"\x1B[39m\x1B[33m:\x1B[39m\x1B[32m"uint256"\x1B[39m\x1B[33m,\x1B[39m\x1B[32m"name"\x1B[39m\x1B[33m:\x1B[39m\x1B[32m""\x1B[39m\x1B[33m,\x1B[39m\x1B[32m"type"\x1B[39m\x1B[33m:\x1B[39m\x1B[32m"uint256"\x1B[39m}\x1B[33m>\x1B[39m}\x1B[33m;\x1B[39m\x1B[0m\n' +
    '\x1B[0m \x1B[90m 55 |\x1B[39m                 log\x1B[33m:\x1B[39m \x1B[33mLog\x1B[39m\x1B[33m;\x1B[39m\x1B[0m\n' +
    '\x1B[0m \x1B[90m 56 |\x1B[39m                 block\x1B[33m:\x1B[39m \x1B[33mBlock\x1B[39m\x1B[33m;\x1B[39m\x1B[0m'
}

Node.js v18.7.0
node:internal/errors:856
```

This error is caused by anonymous event params in the `PairCreated` event

```
event PairCreated(address indexed token0, address indexed token1, address pair, uint);
```

that produce the following ABI:

```json
{
   "anonymous":false,
   "inputs":[
      {
         "indexed":true,
         "internalType":"address",
         "name":"token0",
         "type":"address"
      },
      {
         "indexed":true,
         "internalType":"address",
         "name":"token1",
         "type":"address"
      },
      {
         "indexed":false,
         "internalType":"address",
         "name":"pair",
         "type":"address"
      },
      {
         "indexed":false,
         "internalType":"uint256",
         "name":"",
         "type":"uint256"
      }
   ],
   "name":"PairCreated",
   "type":"event"
}
```

and break this code https://github.com/0xOlias/ponder/blob/2f5b67973dfd03f4f883cdf1a8dcc3eccf64b3bb/packages/core/src/codegen/buildEventTypes.ts#L5

```
  51 |                 AbiParameterToPrimitiveType<{"indexed":true,"internalType":"address","name":"token0","type":"address"}>;token1:
  52 |                 AbiParameterToPrimitiveType<{"indexed":true,"internalType":"address","name":"token1","type":"address"}>;pair:
> 53 |                 AbiParameterToPrimitiveType<{"indexed":false,"internalType":"address","name":"pair","type":"address"}>;:
``` 

notice that line 53 it generate empty property key.

**Comment by 0xOlias** [comment]
Thanks for the thorough report! The issue is that Ponder currently assumes every event parameter has a name, but as demonstrated here the name can be `""`.

Looks like `graph codegen` calls unnamed parameters `param${index}`, so in the example above the anonymous `uint` argument would be called `param3`. I don't love that naming scheme, but it is simple enough. Any ideas for improvement?

IIRC viem doesn't run into this issue because ABI item inputs/outputs are strictly-typed tuples rather than objects with a (named) property for each parameter. Personally, I think being able to see the parameter names is a big readability win, so I'd like to continue doing that.
