### ISSUE TITLE
[BUG] When using custom filters, handers are firing twice

### ISSUE THREAD

**Issue by crazyrabbitLTC** [0xOlias/ponder#396]
I am finding that I am hitting Unique SQL constraint errors. When digging in it seems my handlers are firing twice. 

My error: 

```01:37:42.299 ERROR app        Unable to decode log (skipping it): [object Object]
DecodeLogTopicsMismatch: Expected a topic for indexed event parameter "previousOwner" on event "OwnershipTransferred(address previousOwner, address newOwner)".

Version: viem@1.16.5
    at decodeEventLog (/Users/dennisonbertram/Develop/auto-ponder/node_modules/viem/_cjs/utils/abi/decodeEventLog.js:30:19)
    at /Users/dennisonbertram/Develop/auto-ponder/node_modules/@ponder/core/dist/event-aggregator/service.js:77:66
    at Array.reduce (<anonymous>)
    at EventAggregatorService.getEvents (/Users/dennisonbertram/Develop/auto-ponder/node_modules/@ponder/core/dist/event-aggregator/service.js:66:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/dennisonbertram/Develop/auto-ponder/node_modules/@ponder/core/dist/user-handlers/service.js:208:34
Am I firing twice? 0x81a28c76b0e3c86720e899e388f12c21d3c1d09762beba02e277b5b412cd8fef-0xb9
Am I firing twice? 0x81a28c76b0e3c86720e899e388f12c21d3c1d09762beba02e277b5b412cd8fef-0xb9
01:37:42.551 ERROR handlers   Error while handling "ERC20Votes_Ownable:OwnershipTransferred" event at block 17000001: SQLite error: UNIQUE constraint failed: OwnershipTransferred_EVENT_a57756f6.id, OwnershipTransferred_EVENT_a57756f6.effectiveTo
Statement:
  insert into "OwnershipTransferred_EVENT_a57756f6" ("id", "previousOwner", "newOwner", "contract", "block", "transaction", "log", "effectiveFrom", "effectiveTo") values (?, ?, ?, ?, ?, ?, ?, ?, ?) returning *
Parameters:
  1:  0x81a28c76b0e3c86720e899e388f12c21d3c1d09762beba02e277b5b412cd8fef-0xb9-Ownershi...
  2:  0x0000000000000000000000000000000000000000
  3:  0xd12c6E1Ee11997d4f97f5F13F3060178A74Cd49E
  4:  0x55a35e9e0faadc8e04a47e2436f8b9cb87d1dd81
  5:  0x81a28c76b0e3c86720e899e388f12c21d3c1d09762beba02e277b5b412cd8fef
  6:  0xdc477f979e53c946ef84a4e49fe1a176655d9c6167b3bdf1866967f6b3fa1450
  7:  0x81a28c76b0e3c86720e899e388f12c21d3c1d09762beba02e277b5b412cd8fef-0xb9
  8:  1680911903
  9:  2147483647

  at async Object.fn (/Users/dennisonbertram/Develop/auto-ponder/src/handlers/ERC20/registerOwnershipTransfered.ts:10:4)
   8 |   const { newBlock, newTransaction, newLog, sender, contract } = await createCommonEntities(event, context);
   9 |
> 10 |     await OwnershipTransferred_EVENT.create({
     |    ^
  11 |       id: `${event.log.id}-OwnershipTransferred`,
  12 |       data: {
  13 |         previousOwner: event.params.previousOwner,
Event params:
  previousOwner:  0x0000000000000000000000000000000000000000
  newOwner:       0xd12c6E1Ee11997d4f97f5F13F3060178A74Cd49E
01:37:42.551 INFO  handlers   Processed 8148 events (up to Apr 8, 2023)
```

Take note of the line: 

```
Am I firing twice? 0x81a28c76b0e3c86720e899e388f12c21d3c1d09762beba02e277b5b412cd8fef-0xb9
Am I firing twice? 0x81a28c76b0e3c86720e899e388f12c21d3c1d09762beba02e277b5b412cd8fef-0xb9
```

This comes from my code: 

```import { ponder } from "@/generated";
import { createCommonEntities } from "../../utils";

export function registerOwnershipTransferredEvent() {
  ponder.on("ERC20Votes_Ownable:OwnershipTransferred", async ({ event, context }) => {
    console.log("Am I firing twice?", event.log.id)
    const { OwnershipTransferred_EVENT } = context.entities;
  const { newBlock, newTransaction, newLog, sender, contract } = await createCommonEntities(event, context);

    await OwnershipTransferred_EVENT.create({
      id: `${event.log.id}-OwnershipTransferred`,
      data: {
        previousOwner: event.params.previousOwner,
        newOwner: event.params.newOwner,
        contract: contract.id,
        block: newBlock.id,
        transaction: newTransaction.id,
        log: newLog.id,
      },
    });
  });
}
```

This filter is described like this: 

```  {
    name: "ERC20Votes_Ownable",
    network: "mainnet",
    startBlock: 17000000,
    abi: "/Users/dennisonbertram/Develop/auto-ponder/abis/ERC20Votes_Ownable.json",
    filter: {
      event: parseAbiItem("event OwnershipTransferred(address indexed previousOwner, address indexed newOwner)")
    }
  },
  ```

**Comment by crazyrabbitLTC** [comment]
I just updated to the latest (.93) and this problem seems to have gone away so I'll close this.

**Comment by crazyrabbitLTC** [comment]
Sorry that was premature, the problem with the duplicate handler firing is still there.
