### ISSUE TITLE
[BUG]: Response from RPC provider is too large

### ISSUE THREAD

**Issue by crazyrabbitLTC** [0xOlias/ponder#407]
Tried indexing ERC20 Transfers on all contract (just to see what happened) 

Got this error: 

```
Status: 400
URL: https://eth-mainnet.g.alchemy.com/v2/-cmjJLKILharAWRSmsZBT1xD42bhxpOU
Request body: {"method":"eth_getLogs","params":[{"topics":["0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef"],"fromBlock":"0x1143172","toBlock":"0x1143941"}]}

Details: {"code":-32600,"message":"Response size is larger than 150MB limit"}
Version: viem@1.16.5
    at Object.http (/Users/dennisonbertram/Develop/auto-ponder/node_modules/viem/_cjs/utils/rpc.js:44:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fn (/Users/dennisonbertram/Develop/auto-ponder/node_modules/viem/_cjs/clients/transports/http.js:37:24)
    at async request (/Users/dennisonbertram/Develop/auto-ponder/node_modules/viem/_cjs/clients/transports/http.js:38:45)
    at async delay.count.count (/Users/dennisonbertram/Develop/auto-ponder/node_modules/viem/_cjs/utils/buildRequest.js:30:20)
    at async attemptRetry (/Users/dennisonbertram/Develop/auto-ponder/node_modules/viem/_cjs/utils/promise/withRetry.js:15:30)
18:59:48.702 ERROR historical Log filter task failed, retrying... [18104594, 18106593] (logFilter=ERC20Votes_Ownable, network=mainnet)
RangeError: Maximum call stack size exceeded
    at HistoricalSyncService._eth_getLogs (/Users/dennisonbertram/Develop/auto-ponder/node_modules/@ponder/core/dist/historical-sync/service.js:572:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async HistoricalSyncService.logFilterTaskWorker (/Users/dennisonbertram/Develop/auto-ponder/node_modules/@ponder/core/dist/historical-sync/service.js:362:22)
    at async worker (/Users/dennisonbertram/Develop/auto-ponder/node_modules/@ponder/core/dist/historical-sync/service.js:280:21)
    at async queue.add.priority.priority (/Users/dennisonbertram/Develop/auto-ponder/node_modules/@ponder/core/dist/utils/queue.js:57:26)
    at async run (/Users/dennisonbertram/Develop/auto-ponder/node_modules/p-queue/dist/index.js:163:29)
18:59:51.763 ERROR historical Log filter task failed, retrying... [18100594, 18102593] (logFilter=ERC20Votes_Ownable, network=mainnet)
HttpRequestError: HTTP request failed.
```

**Comment by 0xOlias** [comment]
This should be fixed in `0.0.95`.
