### ISSUE TITLE
[Bug]: Blocks are added out of order

### ISSUE THREAD

**Issue by crazyrabbitLTC** [0xOlias/ponder#408]
Not much context here on Ponder .94 I'm getting this error (sometimes), after stopping indexing and starting again. 

```19:03:34.283 ERROR historical Log filter task failed, retrying... [18106594, 18108593] (logFilter=OZGovernorProposalCreated, network=mainnet)
Error: New pending block number 18106235 was added out of order. Already added block number 18106593.
    at BlockProgressTracker.addPendingBlocks (/Users/dennisonbertram/Develop/auto-ponder/node_modules/@ponder/core/dist/utils/interval.js:289:19)
    at HistoricalSyncService.enqueueBlockTasks (/Users/dennisonbertram/Develop/auto-ponder/node_modules/@ponder/core/dist/historical-sync/service.js:551:39)
    at HistoricalSyncService.logFilterTaskWorker (/Users/dennisonbertram/Develop/auto-ponder/node_modules/@ponder/core/dist/historical-sync/service.js:390:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async worker (/Users/dennisonbertram/Develop/auto-ponder/node_modules/@ponder/core/dist/historical-sync/service.js:280:21)
    at async queue.add.priority.priority (/Users/dennisonbertram/Develop/auto-ponder/node_modules/@ponder/core/dist/utils/queue.js:57:26)
    at async run (/Users/dennisonbertram/Develop/auto-ponder/node_modules/p-queue/dist/index.js:163:29)
dennisonbertram@Dennisons-MacBook-Air auto-ponder % ```

**Comment by 0xOlias** [comment]
Thanks for reporting. This is a new bug introduced in the latest release. Could you share your config file? And what specifically do you mean by "after stopping indexing and starting again"? Are you killing the process and running `pnpm dev` again?

**Comment by crazyrabbitLTC** [comment]
Yes I'm killing the process and running `npx ponder dev`. This is the repo: https://github.com/crazyrabbitLTC/ponder-testing

As a note, I didn't have this happen after I updated the handlers which had the clashing definitions, so I'm not sure if that solved it or not.
